version: '3'
services:

  mariadb:
    container_name: mariadbCompose
    restart: always
    build:
      context: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - /home/tchevrie/db:/var/lib/mysql
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  
  wordpress:
    container_name: wordpressCompose
    restart: always
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - /home/tchevrie/wordpress:/var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb

  nginx:
    container_name: nginxCompose
    restart: always
    build:
      context: ./requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - /home/tchevrie/wordpress:/var/www/html:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  db_data: