version: '3'
services:

  mariadb:
    container_name: mariadbCompose
    restart: always
    build:
      context: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - ../tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  
  wordpress:
    container_name: wordpressCompose
    restart: always
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - ../tmp/wordpress:/var/www/html
    depends_on:
      - mariadb

  nginx:
    container_name: nginxCompose
    restart: always
    build:
      context: ./requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - ../tmp/wordpress:/var/www/html:ro
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  db_data: