version: '3'
services:
  wordpress:
    container_name: wordpressCompose
    restart: always
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    ports:
      - 9000:9000
    volumes:
      - ../wordpress:/var/www/html
  nginx:
    container_name: nginxCompose
    restart: always
    build:
      context: ./requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - ../wordpress:/var/www/html:ro
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  db_data: