version: '3'
services:
  nginx:
    container_name: nginxCompose
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../wordpress:/var/www/html

volumes:
  wordpress:
  db_data: