CREATE DATABASE IF NOT EXISTS {{DB_NAME}};
CREATE USER IF NOT EXISTS '{{DB_USER}}'@'%' IDENTIFIED BY '{{DB_PASSWORD}}';
DROP USER 'root'@'localhost';
GRANT ALL PRIVILEGES ON {{DB_NAME}}.* TO '{{DB_USER}}'@'%';
